### ISSUE TITLE
Update install docs for Windows behind proxy

### ISSUE THREAD

**Issue by trnielsen** [mccode-dev/McCode#687]
McStas 2.5.rc07 for Win10_64 does not install when user is behind a proxy. Conda does not auto detect the system proxy, even if it is set.

In the terminal one needs set the proxy, and the run the install script (as root) 

> set HTTP_PROXY=http://your_proxy_ip:port
or

> set HTTPS_PROXY=http://your_proxy_ip:port

We should add this in
•	Release notes
•	On the wiki in “known issues” section
•	In install section on mcstas.org

**Comment by willend** [comment]
@trnielsen I added a snippet at 
https://github.com/McStasMcXtrace/McCode/wiki/Known-issues-and-FAQ%27s

Could you try what happens if one sets the variable in a shell from which one launches the "normal" installer? I have no Windows behind a proxy to try with myself...

**Comment by willend** [comment]
Running a local squid proxy on my Mac and connecting a VM to that, I have found that 
* Opening a cmd.exe shell
* set HTTP_PROXY=http://your_proxy_ip:port
* Run the McStas installer from that shell
seems to work (I interrupted the proxy server during install and conda started having issues)

I personally think
https://github.com/McStasMcXtrace/McCode/wiki/Known-issues-and-FAQ%27s should be enough - perhaps also putting a link to these known issues in every install page / README file

**Comment by trnielsen** [comment]
Proxy setting are mentioned on the wiki here

https://github.com/McStasMcXtrace/McCode/wiki/Known-issues-and-FAQ%27s

https://github.com/McStasMcXtrace/McCode/wiki/Building-McStas-McXtrace
